/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package alende.clientermi.chat.Views;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author frana
 */
public class ChatView extends javax.swing.JDialog {
     private DefaultListModel<String> users = new DefaultListModel<>();

    /**
     * Creates new form ChatView
     */
    public ChatView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UsuariosList.setModel(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UsuariosList = new javax.swing.JList<>();
        EnviarjButton = new javax.swing.JButton();
        MensajeTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MensajesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(UsuariosList);

        EnviarjButton.setText("Enviar");

        MensajeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajeTextFieldActionPerformed(evt);
            }
        });

        MensajesTextArea.setColumns(20);
        MensajesTextArea.setRows(5);
        jScrollPane2.setViewportView(MensajesTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MensajeTextField)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(EnviarjButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnviarjButton)
                    .addComponent(MensajeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MensajeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MensajeTextFieldActionPerformed

public String getMensaje(){
    return this.MensajeTextField.getText();
}
 public void pressEnviarButton(ActionListener al){
    this.EnviarjButton.addActionListener(al);
    }
 public void mostrarUsuarios(List<String> usuarios) {
        users.clear();
        for (String u :usuarios) {
            users.addElement(u);
        }

    }
  public String getUser() {
        return UsuariosList.getSelectedValue();
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarjButton;
    private javax.swing.JTextField MensajeTextField;
    private javax.swing.JTextArea MensajesTextArea;
    private javax.swing.JList<String> UsuariosList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
